# Docker Compose file for Observium
# Maintained by somsakc@hotmail.com

services:
  db:
    image: mariadb:11.7
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=observium
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=observium
      - TZ=Asia/Bangkok
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - back-tier
    restart: unless-stopped

  app:
    image: mbixtech/observium:24.12
    environment:
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=passw0rd
      - OBSERVIUM_DB_HOST=db
      - OBSERVIUM_DB_NAME=observium
      - OBSERVIUM_DB_USER=observium
      - OBSERVIUM_DB_PASS=passw0rd
      - OBSERVIUM_BASE_URL=http://localhost:8888
      - TZ=Asia/Bangkok
    volumes:
      - ./logs:/opt/observium/logs
      - ./rrd:/opt/observium/rrd
    networks:
      - back-tier
    ports:
      - "8888:80"
    restart: unless-stopped
    depends_on:
      - db

networks:
  back-tier:
      driver: bridge
